### ISSUE TITLE
Hi, I see that in your paper you used three types of synthetic defect images to train the pixelwise refinement network, but I didn’t find the relevant ones in the code. Can you point out which file the specific code is in?

### ISSUE THREAD

**Issue by sevenn126** [wogur110/PNI_Anomaly_Detection#2]

**Comment by wogur110** [comment]
Hi. main/pixelwise_refinement.py is the specific code what you mentioned.

**Comment by StefanoSamele-PoliMi** [comment]
Hi, thank you for sharing your exciting work. I was wondering if you could also share the code to prepare the images used to train the refinement network. My understanding is that main/pixelwise_refinement.py is just a script that does the training/evaluation, but the images are pre-prepared and stored under the location indicated by --input_data_path argument.

**Comment by wogur110** [comment]
Hi, I prepared the images for training the refinement network using 1) DREAM, 2) CutPaste, and 3) manual data. For DREAM and CutPaste, I made the dataset using existing official codes, so it is not necessary to share the codes. For manual data, I can share synthetic datasets, but I'm not sure if I can share MVTec data directly. If you want, I will share the manual data only.

**Comment by StefanoSamele-PoliMi** [comment]
Thank you for the follow-up. I am not interested in the specific MVTec dataset but rather in the procedure you adopted for creating the manual data: can I kindly ask you if you can give more details about the types of drawings and synthetic anomalies you inserted? Do they change from class to class? Maybe just a few key examples could let us understand. Thank you in advance for your support.
