### ISSUE TITLE
inference time about PNI

### ISSUE THREAD

**Issue by david990705** [wogur110/PNI_anomaly_detection#4]
We run the official code you provided and find that we can't reproduce the metrics in the paper, meanwhile we test the inference time for a single image on RTX 3090 is about 20s per image, the image size is 480*480. We feel that there is a big problem with this inference time, can you help to answer the questions?

**Comment by Kerio99** [comment]
same problem~

**Comment by YuRongHao2233** [comment]
@wogur110

**Comment by gitfri021** [comment]
same issue @wogur110
