### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './result/bottle/WR101/anomaly/lightning_logs'

### ISSUE THREAD

**Issue by cjy513203427** [wogur110/PNI_anomaly_detection#5]
`(py38) cjy@cjy-CP65S:/data/pycharm_project/PNI_anomaly_detection$ python analysis_code/calc_ensemble_score.py --category bottle --backbone_list WR101 --project_root_path ./result --ensemble_root_path ./result/WR101
Start ensemble bottle!
Traceback (most recent call last):
  File "analysis_code/calc_ensemble_score.py", line 95, in <module>
    result_version_list = os.listdir(default_root_dir)
FileNotFoundError: [Errno 2] No such file or directory: './result/bottle/WR101/anomaly/lightning_logs'`

When I tried to run `./evaluate_amap_on_MVTecAD_WR101.sh`, I met error above

**Comment by KajetanPoliak** [comment]
Same for me
